# Generated by Django 5.0.2 on 2024-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('auth0_name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('picture', models.URLField(max_length=300)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Completed', 'Completed')], default='Current', max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('grade', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('course_image', models.URLField(blank=True, max_length=300)),
                ('users', models.ManyToManyField(blank=True, to='backend.user')),
            ],
        ),
    ]
