# Generated by Django 5.0.2 on 2024-03-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
    ]
