# Generated by Django 5.0.2 on 2024-03-31 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('total_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EngagementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('start', models.FloatField()),
                ('duration', models.FloatField()),
                ('end', models.FloatField()),
                ('engagement_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_periods', to='backend.engagementdata')),
            ],
        ),
    ]
