# Generated by Django 5.0.2 on 2024-04-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.assignment')),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
            ],
        ),
    ]
