# Generated by Django 5.0.2 on 2024-04-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_engagementdata_engagementperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementdata',
            name='engaged_time',
            field=models.FloatField(default=0),
        ),
    ]
