# Generated by Django 5.0.2 on 2024-04-14 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_userquestion_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementdata',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engagementdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
            preserve_default=False,
        ),
    ]
