# Generated by Django 5.0.2 on 2024-04-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_assignmentgrade_coursegrade'),
        ('backend', '0003_engagementdata_engaged_time'),
    ]

    operations = [
    ]
