# Generated by Django 5.0.2 on 2024-04-15 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_engagementdata_activity_engagementdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementdata',
            name='activity',
        ),
        migrations.AddField(
            model_name='engagementdata',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.assignment'),
            preserve_default=False,
        ),
    ]
