# Generated by Django 5.0.2 on 2024-04-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_engagementdata_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='user_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
