# Generated by Django 5.0.2 on 2024-04-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_userquestion_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
