# Generated by Django 5.0.2 on 2024-04-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='auth_id',
            new_name='user',
        ),
    ]
