# Generated by Django 5.0.2 on 2024-03-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_coursename_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('auth0_name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('picture', models.URLField(max_length=300)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
