# Generated by Django 5.0.2 on 2024-03-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_section_assignment'),
        ('backend', '0009_user'),
    ]

    operations = [
    ]
