# Generated by Django 5.0.2 on 2024-03-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_merge_0009_section_assignment_0009_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to='backend.user'),
        ),
    ]
