# Generated by Django 5.0.2 on 2024-03-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_course_instructor_remove_course_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='sections',
            field=models.ManyToManyField(null=True, to='backend.section'),
        ),
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(null=True, to='backend.user'),
        ),
    ]
