# Generated by Django 5.0.2 on 2024-03-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_course_sections_alter_course_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sections',
            field=models.ManyToManyField(blank=True, to='backend.section'),
        ),
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(blank=True, to='backend.user'),
        ),
    ]
